# Generated by Django 4.2.18 on 2025-03-17 17:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('app', '0002_alter_bill_options_remove_bill_reminder_sent_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReminderSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email_reminders', models.BooleanField(default=True)),
                ('push_notifications', models.BooleanField(default=True)),
                ('default_reminder_days', models.IntegerField(default=3)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='reminder_settings', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Reminder Settings',
                'verbose_name_plural': 'Reminder Settings',
            },
        ),
    ]
