# Generated by Django 4.2.18 on 2025-03-18 04:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_remindersettings'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='paid_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.CreateModel(
            name='BillActivity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('payment', 'Payment'), ('reminder', 'Reminder'), ('update', 'Update')], max_length=20)),
                ('message', models.CharField(max_length=255)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('bill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='app.bill')),
            ],
            options={
                'verbose_name': 'Bill Activity',
                'verbose_name_plural': 'Bill Activities',
                'ordering': ['-timestamp'],
            },
        ),
    ]
