# Generated by Django 4.2.10 on 2025-04-05 05:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_bill_paid_date_billactivity'),
    ]

    operations = [
        migrations.AddField(
            model_name='bill',
            name='last_reminder_sent',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bill',
            name='reminder_sent',
            field=models.BooleanField(default=False),
        ),
    ]
