# Generated by Django 4.2.10 on 2025-04-05 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_bill_last_reminder_sent_bill_reminder_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='reset_otp',
            field=models.CharField(blank=True, max_length=6, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='reset_otp_created_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
